version: "3.7"
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 8888:80
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel
        restart: always

    php:
        build: 
            context: .
            dockerfile: DockerFile
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - 9000:80
        networks:
            - laravel
    
    mysql:
        image: mysql:8.0
        ports:
            - 33061:3306
        container_name: mysql
        environment:
            - MYSQL_DATABASE=polimundo
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=adminPolimund0
            - MYSQL_ROOT_PASSWORD=rootPolimundo
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - laravel
    
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_HOST=mysql
            - MYSQL_ROOT_PASSWORD=password
        expose:
            - 80
        ports:
            - 8081:80
        networks:
            - laravel

networks:
    laravel: